config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root to: 'pages#home'
  root 'pages#home'



  namespace :admin do
    root 'dashboard#index'
    resources :categories
    resources :products
  end

  namespace :user do
    root 'home#index'
  end

end

app/models/admin/category.rb
class Admin::Category < ApplicationRecord
  has_many :cat_prods
  has_many :products, through: :cat_prods
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_admin_category, only: %i[ show edit update destroy ]

  # GET /admin/categories or /admin/categories.json
  def index
    @admin_categories = Admin::Category.all
  end

  # GET /admin/categories/1 or /admin/categories/1.json
  def show
  end

  # GET /admin/categories/new
  def new
    @admin_category = Admin::Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories or /admin/categories.json
  def create
    @admin_category = Admin::Category.new(admin_category_params)

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to admin_category_url(@admin_category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @admin_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1 or /admin/categories/1.json
  def update
    respond_to do |format|
      if @admin_category.update(admin_category_params)
        format.html { redirect_to admin_category_url(@admin_category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1 or /admin/categories/1.json
  def destroy
    @admin_category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_category
      @admin_category = Admin::Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_category_params
      params.require(:admin_category).permit(:title)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Title:</strong>
    <%= category.title %>
  </p>

</div>

app/views/admin/categories/_form.html.erb
<%= form_with(model: admin_category) do |form| %>
  <% if admin_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_category.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
        <% admin_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", admin_category: @admin_category %>

<br>

<div>
  <%= link_to "Show this category", @admin_category %> |
  <%= link_to "Back to categories", admin_categories_path %>
</div>

app/views/admin/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="admin_categories">
  <% @admin_categories.each do |admin_category| %>
    <%= render admin_category %>
    <p>
      <%= link_to "Show this category", admin_category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New category</h1>

<%= render "form", admin_category: @admin_category %>

<br>

<div>
  <%= link_to "Back to categories", admin_categories_path %>
</div>

app/views/admin/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_category %>

<div>
  <%= link_to "Edit this category", edit_admin_category_path(@admin_category) %> |
  <%= link_to "Back to categories", admin_categories_path %>

  <%= button_to "Destroy this category", @admin_category, method: :delete %>
</div>